name: "Hello Github Actions"

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'
  workflow_dispatch:

jobs:
  hello-job:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4

      - name: "Execute Hello World"
        run: echo "Hello, world!"

      - name: "Show system information"
        run: |
          echo "Operating System: $(uname -s)"
          echo "Architecture: $(uname -m)"
          echo "GitHub Runner: ${{ runner.name }}"
          echo "GitHub Workspace: ${{ github.workspace }}"
          echo "OS ${{ runner.os }}"

      - name: "List files in the workspace"
        run: ls -la ${{ github.workspace }}
      
      - name: "Who I am?"
        run: whoami
